name: agito
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - altgraph==0.17.4
    - blinker==1.8.2
    - click==8.1.8
    - contourpy==1.1.1
    - cycler==0.12.1
    - filelock==3.16.1
    - flask==3.0.3
    - fonttools==4.56.0
    - fsspec==2025.2.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - itsdangerous==2.2.0
    - jinja2==3.1.5
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - llvmlite==0.41.1
    - logomaker==0.8.6
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mpmath==1.3.0
    - networkx==3.1
    - numba==0.58.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.1.105
    - packaging==24.2
    - pandas==2.0.3
    - pillow==10.4.0
    - plot==0.6.5
    - pybigwig==0.3.22
    - pyfaidx==0.8.1.3
    - pyinstaller==6.12.0
    - pyinstaller-hooks-contrib==2025.1
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pyyaml==6.0.2
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.17.0
    - sympy==1.13.3
    - tangermeme==0.4.3
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - torch==2.4.1
    - tqdm==4.67.1
    - triton==3.0.0
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - werkzeug==3.0.6
    - zipp==3.20.2
prefix: /home/tg/.conda/envs/kuuga
